name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Perform build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Install Dependancies
        run: npm install --legacy-peer-deps

      - name: Generate prisma client
        run: npm run db:genarate

      - name: Run build
        run: npm run build
